#!/usr/bin/env python3
"""Render the Herdr compatibility matrix from the gates that produce the evidence."""

from __future__ import annotations

import argparse
from pathlib import Path
import re
import sys
import textwrap
import tomllib

MAX_INPUT_BYTES = 512 * 1024

DOCUMENT = Path("docs/compatibility.md")
STABLE_GATE = Path(".github/workflows/live-product-core.yml")
CANARY_GATE = Path(".github/workflows/upstream-canary.yml")
PROTOCOL_SOURCE = Path("src/herdr_socket.rs")
PLUGIN_MANIFEST = Path("herdr-plugin.toml")
PACKAGE_MANIFEST = Path("Cargo.toml")

GENERATED_NOTICE = (
    "<!-- Generated by tools/render_compatibility.py. Edit the gates it reads, not this file. -->"
)


class CompatibilityError(RuntimeError):
    """The matrix cannot be derived from the tree."""


def read_bounded(root: Path, relative: Path) -> str:
    path = root / relative
    try:
        if path.stat().st_size > MAX_INPUT_BYTES:
            raise CompatibilityError(f"{relative} exceeds {MAX_INPUT_BYTES} bytes")
        return path.read_text(encoding="utf-8")
    except OSError as error:
        raise CompatibilityError(f"{relative} is unavailable") from error
    except UnicodeError as error:
        raise CompatibilityError(f"{relative} is not UTF-8") from error


def parse_stable_gate(text: str) -> list[tuple[str, str]]:
    """The platforms the stable gate exercises, and the Herdr release on each.

    Read from the gate's own matrix so the document cannot drift from the job
    that produces the evidence. A shape this does not recognize is an error
    rather than an empty matrix: a silently empty table would read as "exercised
    against nothing".
    """
    entries: list[tuple[str, str]] = []
    for block in re.finditer(
        r"- os:\s*\S+\s*\n\s*label:\s*(?P<label>[^\n]+?)\s*\n"
        r"(?:\s*\w+:[^\n]*\n)*?\s*herdr_version:\s*\"(?P<version>[^\"]+)\"",
        text,
    ):
        label = block.group("label").strip()
        version = block.group("version").strip()
        if not label or not version:
            raise CompatibilityError("stable gate matrix has an empty label or version")
        entries.append((label, version))
    if not entries:
        raise CompatibilityError("stable gate matrix has no platform entries")
    return entries


def parse_protocols(text: str) -> dict[str, str]:
    patterns = {
        "minimum": r"pub const MIN_HERDR_PROTOCOL:\s*u32\s*=\s*(\d+)",
        "minimum_label": r"pub const MIN_HERDR_VERSION_LABEL:\s*&str\s*=\s*\"([^\"]+)\"",
        "audited": r"const MAX_AUDITED_HERDR_PROTOCOL:\s*u32\s*=\s*(\d+)",
    }
    values: dict[str, str] = {}
    for name, pattern in patterns.items():
        match = re.search(pattern, text)
        if match is None:
            raise CompatibilityError(f"{PROTOCOL_SOURCE} does not define the {name} protocol")
        values[name] = match.group(1)
    return values


def load_version(root: Path, relative: Path) -> str:
    document = tomllib.loads(read_bounded(root, relative))
    table = document.get("package", document)
    version = table.get("version")
    if not isinstance(version, str) or not version:
        raise CompatibilityError(f"{relative} has no version")
    return version


def render(root: Path) -> str:
    tether_version = load_version(root, PACKAGE_MANIFEST)
    manifest_minimum = tomllib.loads(read_bounded(root, PLUGIN_MANIFEST)).get("min_herdr_version")
    protocols = parse_protocols(read_bounded(root, PROTOCOL_SOURCE))
    if manifest_minimum != protocols["minimum_label"]:
        raise CompatibilityError(
            f"{PLUGIN_MANIFEST} minimum {manifest_minimum!r} does not match "
            f"the source label {protocols['minimum_label']!r}"
        )
    platforms = parse_stable_gate(read_bounded(root, STABLE_GATE))
    exercised = ", ".join(sorted({version for _, version in platforms}))

    table = ["| Platform | Herdr release | How it was exercised |", "| --- | --- | --- |"]
    table.extend(
        f"| {label} | {version} | Official release asset, verified by SHA-256, "
        "then the live product smoke |"
        for label, version in platforms
    )

    paragraphs: list[str] = [
        f"# Herdr compatibility",
        GENERATED_NOTICE,
        f"Which Herdr releases Tether {tether_version} was exercised against, so it"
        " can be checked before installing rather than inferred from a version"
        " requirement.",
        "## Exercised",
        "\n".join(table),
        "Every row is a real run: the gate downloads the official Herdr release"
        " asset for the runner's platform, verifies it against a pinned SHA-256,"
        " validates the socket API schema it reports, builds Tether from the locked"
        " manifest, and drives a workload through `tmux` end to end. A row exists"
        " only for a platform that gate actually covers.",
        "## Socket protocol",
        f"Tether speaks Herdr's socket API from protocol {protocols['minimum']},"
        f" which Herdr {protocols['minimum_label']} ships, and its checks cover"
        f" through protocol {protocols['audited']}. A Herdr reporting a protocol"
        f" above {protocols['audited']} is not refused: `herdr-tether doctor`"
        " reports it as newer and not yet verified, and Tether keeps working with"
        " the parts of the API it knows. A Herdr below protocol"
        f" {protocols['minimum']} is refused, because the requests Tether depends"
        " on are absent.",
        "## What this does not claim",
        f"Herdr releases other than {exercised} are not covered here. Tether may"
        " work with them, and its protocol floor is the real compatibility boundary"
        " at runtime, but this table says only what was exercised.",
        "Unreleased upstream Herdr is exercised separately, on a schedule, against"
        " whatever `master` resolves to at the time. That canary is advisory: it"
        " catches breakage early, and a moving revision is not something a user can"
        " install, so it is deliberately absent from this table. Its behaviour"
        " reaches this document only once it ships in a Herdr release the stable"
        " gate pins.",
    ]
    wrapped = [
        paragraph
        if paragraph.startswith(("#", "|", "<!--"))
        else textwrap.fill(paragraph, width=80)
        for paragraph in paragraphs
    ]
    return "\n\n".join(wrapped) + "\n"


def check(root: Path) -> list[str]:
    try:
        expected = render(root)
    except CompatibilityError as error:
        return [str(error)]
    path = root / DOCUMENT
    if not path.is_file():
        return [f"{DOCUMENT} is missing; run tools/render_compatibility.py --write"]
    try:
        actual = read_bounded(root, DOCUMENT)
    except CompatibilityError as error:
        return [str(error)]
    if actual != expected:
        return [
            f"{DOCUMENT} does not match the gates it is derived from; "
            "run tools/render_compatibility.py --write"
        ]
    return []


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument(
        "--write",
        action="store_true",
        help="regenerate the document instead of verifying it",
    )
    args = parser.parse_args(argv)
    root = args.root.resolve()
    if args.write:
        try:
            (root / DOCUMENT).write_text(render(root), encoding="utf-8")
        except (CompatibilityError, OSError) as error:
            print(f"compatibility matrix error: {error}", file=sys.stderr)
            return 1
        print(f"compatibility matrix written: {DOCUMENT}")
        return 0
    findings = check(root)
    for finding in findings:
        print(f"compatibility matrix error: {finding}", file=sys.stderr)
    if findings:
        return 1
    print("compatibility matrix verified")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
