#!/usr/bin/env python3
"""Render the Herdr compatibility matrix from the gates that produce the evidence."""

from __future__ import annotations

import argparse
from pathlib import Path
import re
import sys
import textwrap
import tomllib

MAX_INPUT_BYTES = 512 * 1024

DOCUMENT = Path("docs/compatibility.md")
STABLE_GATE = Path(".github/workflows/live-product-core.yml")
CANARY_GATE = Path(".github/workflows/upstream-canary.yml")
PROTOCOL_SOURCE = Path("src/herdr_socket.rs")
PLUGIN_MANIFEST = Path("herdr-plugin.toml")
PACKAGE_MANIFEST = Path("Cargo.toml")

STABLE_GATE_JOB = "live-product"

GENERATED_NOTICE = (
    "<!-- Generated by tools/render_compatibility.py. Edit the gates it reads, not this file. -->"
)


class CompatibilityError(RuntimeError):
    """The matrix cannot be derived from the tree."""


def read_bounded(root: Path, relative: Path) -> str:
    path = root / relative
    try:
        if path.stat().st_size > MAX_INPUT_BYTES:
            raise CompatibilityError(f"{relative} exceeds {MAX_INPUT_BYTES} bytes")
        return path.read_text(encoding="utf-8")
    except OSError as error:
        raise CompatibilityError(f"{relative} is unavailable") from error
    except UnicodeError as error:
        raise CompatibilityError(f"{relative} is not UTF-8") from error


def job_block(text: str, job: str) -> str:
    """The lines of one workflow job, so another job's matrix cannot contribute rows."""
    heading = re.search(rf"^(?P<indent>\s+){re.escape(job)}:\s*$", text, re.M)
    if heading is None:
        raise CompatibilityError(f"{STABLE_GATE} has no `{job}` job")
    indent = len(heading.group("indent"))
    lines = text[heading.end() :].splitlines()
    block: list[str] = []
    for line in lines:
        if line.strip() and len(line) - len(line.lstrip()) <= indent:
            break
        block.append(line)
    return "\n".join(block)


def scalar(value: str) -> str:
    """A YAML scalar as written, quoted or not, with any trailing comment removed."""
    value = value.strip()
    if value[:1] in {"'", '"'}:
        quote = value[0]
        end = value.find(quote, 1)
        if end == -1:
            raise CompatibilityError("stable gate matrix has an unterminated quoted value")
        return value[1:end]
    return value.split(" #", 1)[0].strip()


def matrix_entries(block: str) -> list[dict[str, str]]:
    """The `include:` entries of a job's matrix, one dictionary each.

    Parsed entry by entry rather than by one pattern over the whole file. A
    pattern that has to match a whole entry at once skips an entry it does not
    recognize, and a skipped entry means a platform quietly missing from the
    published table — a worse outcome than a failed check, because the table then
    understates what was exercised while every gate stays green.
    """
    entries: list[dict[str, str]] = []
    include_indent: int | None = None
    for line in block.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        indent = len(line) - len(line.lstrip())
        if include_indent is None:
            if stripped == "include:":
                include_indent = indent
            continue
        if indent <= include_indent:
            break
        if stripped.startswith("- "):
            entries.append({})
            stripped = stripped[2:]
        elif not entries:
            raise CompatibilityError("stable gate matrix has a value before its first entry")
        key, separator, value = stripped.partition(":")
        if not separator:
            raise CompatibilityError(f"stable gate matrix has an unreadable line: {stripped!r}")
        entries[-1][key.strip()] = scalar(value)
    if include_indent is None:
        raise CompatibilityError(f"{STABLE_GATE} job `{STABLE_GATE_JOB}` has no matrix include")
    if not entries:
        raise CompatibilityError("stable gate matrix has no platform entries")
    return entries


def parse_stable_gate(text: str) -> list[tuple[str, str]]:
    """The platforms the stable gate exercises, and the Herdr release on each."""
    platforms: list[tuple[str, str]] = []
    for entry in matrix_entries(job_block(text, STABLE_GATE_JOB)):
        label, version = entry.get("label"), entry.get("herdr_version")
        if not label or not version:
            raise CompatibilityError(
                "stable gate matrix entry is missing a label or a herdr_version: "
                f"{sorted(entry)}"
            )
        if "|" in label:
            raise CompatibilityError(f"stable gate label {label!r} cannot appear in a table")
        platforms.append((label, version))
    return platforms


def parse_protocols(text: str) -> dict[str, str]:
    patterns = {
        "minimum": r"pub const MIN_HERDR_PROTOCOL:\s*u32\s*=\s*(\d+)",
        "minimum_label": r"pub const MIN_HERDR_VERSION_LABEL:\s*&str\s*=\s*\"([^\"]+)\"",
        "audited": r"const MAX_AUDITED_HERDR_PROTOCOL:\s*u32\s*=\s*(\d+)",
    }
    values: dict[str, str] = {}
    for name, pattern in patterns.items():
        match = re.search(pattern, text)
        if match is None:
            raise CompatibilityError(f"{PROTOCOL_SOURCE} does not define the {name} protocol")
        values[name] = match.group(1)
    return values


def verify_canary(text: str) -> None:
    """The document says the canary runs on a schedule, so check that it does."""
    if not re.search(r"^\s*schedule:\s*$", text, re.M) or not re.search(r"-\s*cron:", text):
        raise CompatibilityError(f"{CANARY_GATE} has no schedule, which the document claims")


def render(root: Path) -> str:
    manifest_minimum = tomllib.loads(read_bounded(root, PLUGIN_MANIFEST)).get("min_herdr_version")
    protocols = parse_protocols(read_bounded(root, PROTOCOL_SOURCE))
    if manifest_minimum != protocols["minimum_label"]:
        raise CompatibilityError(
            f"{PLUGIN_MANIFEST} minimum {manifest_minimum!r} does not match "
            f"the source label {protocols['minimum_label']!r}"
        )
    platforms = parse_stable_gate(read_bounded(root, STABLE_GATE))
    verify_canary(read_bounded(root, CANARY_GATE))
    exercised = ", ".join(sorted({version for _, version in platforms}))

    table = ["| Platform | Herdr release | How it was exercised |", "| --- | --- | --- |"]
    table.extend(
        f"| {label} | {version} | Official release asset, verified by SHA-256, "
        "then the live product smoke |"
        for label, version in platforms
    )

    paragraphs: list[str] = [
        "# Herdr compatibility",
        GENERATED_NOTICE,
        "Which Herdr releases this revision of Tether was exercised against, so it"
        " can be checked before installing rather than inferred from a version"
        " requirement. At a release tag this file is that release's record; on"
        " `main` it describes `main`.",
        "## Exercised",
        "\n".join(table),
        "Every row is a real run: the gate downloads the official Herdr release"
        " asset for the runner's platform, verifies it against a pinned SHA-256,"
        " validates the socket API schema it reports, builds Tether from the locked"
        " manifest, and drives a workload through `tmux` end to end. A row names"
        " the runner image the gate uses, not every architecture of that operating"
        " system, and a row exists only for a platform the gate actually covers.",
        "## Socket protocol",
        f"Tether speaks Herdr's socket API from protocol {protocols['minimum']},"
        f" which Herdr {protocols['minimum_label']} ships. Its checks audit through"
        f" protocol {protocols['audited']}; that ceiling comes from reviewing newer"
        " upstream Herdr rather than from the releases in the table above, so it"
        " says what Tether has been read against, not what it was run against.",
        f"A Herdr reporting a protocol above {protocols['audited']} is not refused:"
        " `herdr-tether doctor` reports it as newer and not yet verified, and"
        " Tether keeps working with the parts of the API it knows. A Herdr below"
        f" protocol {protocols['minimum']} is not used: Mission Control reports the"
        " upgrade it needs, and the Observer paths report Herdr as not connected"
        " rather than explaining why.",
        "## What this does not claim",
        f"Herdr releases other than {exercised} are not covered here. Tether may"
        " work with them, and its protocol floor is the real compatibility boundary"
        " at runtime, but this table says only what was exercised.",
        "Unreleased upstream Herdr is exercised separately, on a schedule, against"
        " whatever `master` resolves to at the time. That canary is advisory: a"
        " moving revision is not something a user can install, so it contributes no"
        " row here. It is what the audited protocol ceiling above is read against.",
    ]
    wrapped = [
        paragraph
        if paragraph.startswith(("#", "|", "<!--"))
        else textwrap.fill(paragraph, width=80)
        for paragraph in paragraphs
    ]
    return "\n\n".join(wrapped) + "\n"


def check(root: Path) -> list[str]:
    try:
        expected = render(root)
    except CompatibilityError as error:
        return [str(error)]
    path = root / DOCUMENT
    if not path.is_file():
        return [f"{DOCUMENT} is missing; run tools/render_compatibility.py --write"]
    try:
        actual = read_bounded(root, DOCUMENT)
    except CompatibilityError as error:
        return [str(error)]
    if actual != expected:
        return [
            f"{DOCUMENT} does not match the gates it is derived from; "
            "run tools/render_compatibility.py --write"
        ]
    return []


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument(
        "--write",
        action="store_true",
        help="regenerate the document instead of verifying it",
    )
    args = parser.parse_args(argv)
    root = args.root.resolve()
    if args.write:
        try:
            (root / DOCUMENT).write_text(render(root), encoding="utf-8")
        except (CompatibilityError, OSError) as error:
            print(f"compatibility matrix error: {error}", file=sys.stderr)
            return 1
        print(f"compatibility matrix written: {DOCUMENT}")
        return 0
    findings = check(root)
    for finding in findings:
        print(f"compatibility matrix error: {finding}", file=sys.stderr)
    if findings:
        return 1
    print("compatibility matrix verified")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
