pub mod agent_view;
pub mod audit;
pub mod backend;
pub mod cli;
pub mod config;
pub mod discovery;
pub mod herdr;
pub mod herdr_socket;
mod interrupt;
pub mod lifecycle;
pub mod mission_control;
pub mod model;
pub mod observer;
pub mod observer_manager;
pub mod orchestration;
pub mod paths;
pub mod quote;
pub mod snapshot;
pub mod sshcfg;
pub mod state;
pub mod status;
mod storage;
pub mod tmux;
pub mod tui;
